### ISSUE TITLE
Connect to

### ISSUE THREAD

**Issue by sechanbask** [CyrilWaechter/pyRevitMEP#13]
Hello,

I often have this error when I try "connect to"

`IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\Cedric\AppData\Roaming\pyRevit\Extensions\PyRevitMEP.extension\pyRevitMEP.tab\Modify.panel\ConnectTo.pushbutton\script.py", line 100, in 
 File "C:\Users\Cedric\AppData\Roaming\pyRevit\Extensions\PyRevitMEP.extension\pyRevitMEP.tab\Modify.panel\ConnectTo.pushbutton\script.py", line 79, in connect_to
 File "C:\Users\Cedric\AppData\Roaming\pyRevit-Master\pyrevitlib\rpw\db\transaction.py", line 33, in __init__
Exception: The referenced object is not valid, possibly because it has been deleted from the database, or its creation was undone.

Script Executor Traceback:
Autodesk.Revit.Exceptions.InvalidObjectException: The referenced object is not valid, possibly because it has been deleted from the database, or its creation was undone.
 at Microsoft.Scripting.Interpreter.NewInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run5[T0,T1,T2,T3,T4,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at IronPython.Compiler.Ast.CallExpression.Invoke2Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`6.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run5[T0,T1,T2,T3,T4,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
 at IronPython.Runtime.Types.LateBoundInitBinder.FastInitSite`1.CallTarget(CallSite site, CodeContext context, Object inst, T0 arg0)
 at IronPython.Runtime.Types.PythonType.FastTypeSite`1.CallTarget(CallSite site, CodeContext context, Object type, T0 arg0)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitBaseClasses.ScriptExecutor.ExecuteScript(PyRevitCommandRuntime& pyrvtCmd)`

**Comment by CyrilWaechter** [comment]
Hi,

I added some error handling until we figure out better what is really happening. In what case do you get this error ?

Is pyRevit up to date ?
Is pyRevitMEP up to date ?
What Revit version do you use including update release version ?
Can describe step by step your issue ? Give a minimalist rvt where you are to reproduce the error consistently ?

**Comment by sechanbask** [comment]
Hello,

I'm using Revit 2019.2
I have pyRevit 4.6.23 and pyRevitmep last commit 4c8756f 

I am able to reproduce the error on this project,  you can find the project here : 

https://we.tl/t-xGcxqA7HCn

**Comment by CyrilWaechter** [comment]
I am sorry but I get no issue with your file. I am able to connect the flange to the STAF and the opposite.

I am also using 2019.2 french version. I have pyRevit 4.6.24 but it is not supposed to change something.

I know there was some issue with modeless tools in rocket mode but never with modal tools (like ConnectTo). Try to deactivate rocket mode in pyRevit settings just in case.

**Comment by sechanbask** [comment]
Hi,

I do not use french version but ENU. I d'rather because I use dynamo... 

I have the same issue with another file but i have try without rocket mode, it works.


Cédric Barribaud
0621547775

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by CyrilWaechter** [comment]
pyRevitMEP has been updated for pyRevit 4.7.4 #16 Please update and test. A new pyRevit feature may solve the rocket mode issue. Please also try with rocket mode reactivated.

**Comment by CyrilWaechter** [comment]
No answer for about a month. Considered as solved. Reopen it if necessary.
